version: '3'

services: 
  db: 
    image: 'bitnami/mongodb:latest'
    ports:
      - 2717:2717
    restart: on-failure
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - ALLOW_EMPTY_PASSWORD=yes

